services:
  frontend:
    # image: 619071331372.dkr.ecr.us-east-1.amazonaws.com/carpooling-proyect:2.0
    build: ./frontend-chatbot
    ports:
      - 5173:5173

  api-chatbot:
    build: ./Servers/python/flask/src
    container_name: api-chatbot
    ports:
      - 8080:8080
    environment:
      - HUGGING_FACE_API_KEY="tu-api-key"
      - HUGGING_FACE_API_KEY_MOBBEEL = "api-key-mobbeel"
      - OLLAMA_URL_CLIENT = http://ollama:11434
  
  api-mongo:
    build: ./Servers/Database/src
    container_name: api-mongo
    ports:
      - 5000:5000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  
  ollama:
      image: ollama/ollama:latest
      ports:
        - 7869:11434
        # - 11435:11434
      volumes:
        - .:/code
        - ./ollama/ollama:/root/.ollama
      container_name: ollama
      pull_policy: always
      # tty: true
      restart: always
      environment:
        - OLLAMA_KEEP_ALIVE=24h
        - OLLAMA_HOST=0.0.0.0


    