services:
  frontend:
    # image: 619071331372.dkr.ecr.us-east-1.amazonaws.com/carpooling-proyect:2.0
    build: ./frontend-chatbot
    ports:
      - 5173:5173

  api-chatbot:
    build: ./Servers/python/flask/src
    ports:
      - 8080:8080
    environment:
      - HUGGING_FACE_API_KEY="tu-api-key"
      - HUGGING_FACE_API_KEY_MOBBEEL = "api-key-mobbeel"

    